cam_model: Pinhole
cam_width: 640 # 1280
cam_height: 480 # 1024
scale: 0.5
cam_fx: 1293.56944
cam_fy: 1293.3155
cam_cx: 320 #626.91359
cam_cy: 240 #522.799224
cam_d0: -0.076160
cam_d1: 0.123001
cam_d2: -0.00113
cam_d3: 0.000251